# Docker Compose for Solar Monitoring System

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    depends_on:
      - db
      - redis
    # Add device access for Renogy Bluetooth and DS18B20 sensors
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  # For Renogy devices
      - /dev/ttyACM0:/dev/ttyACM0  # Alternative device path
    # Mount 1-Wire interface for DS18B20 sensors
    volumes:
      - .:/app
      - /sys/bus/w1:/sys/bus/w1:ro  # Read-only access to 1-Wire interface

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: solar_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:


